name: Use the Composite Action with Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Image
        run: echo Pretend to build the image

      # Uses the Composite Actone
      - name: Push the image
        uses: n3wt0n/CompositeAction@main        
        with:
          registry_username: ${{secrets.REGISTRY_USERNAME}}
          registry_password: ${{secrets.REGISTRY_PASSWORD}}
          image_name: my-awesome-app
          tag: $GITHUB_RUN_NUMBER
