name: SCMTrigger
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - release/*
  #schedule:
    #- cron: 43 9-16/2 * * 1-5 #this is a comment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: run command
      run: echo Pushed Code
